# Generated by Django 4.2.1 on 2023-05-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homepage__text_rendered_alter_homepage_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='_text_rendered',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text',
            field=models.TextField(),
        ),
    ]
