# Generated by Django 4.2.1 on 2023-06-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_homepage__text_rendered_alter_homepage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='text_et',
            field=models.TextField(default='', verbose_name='Estonian text'),
        ),
    ]
