# Generated by Django 4.2.1 on 2023-05-31 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='owner_name',
            new_name='name',
        ),
    ]
