# Generated by Django 4.2.1 on 2023-05-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='limit',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
