# Generated by Django 4.2.1 on 2023-05-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_tickettype_limit_alter_tickettype_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
    ]
