# Generated by Django 4.2.1 on 2023-05-31 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_tickettype_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='owner_name',
            new_name='name',
        ),
    ]
