# Generated by Django 4.2.1 on 2023-06-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_owner_name_ticket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.CharField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype', verbose_name='Ticket type'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='description',
            field=models.CharField(default='', max_length=512, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='limit',
            field=models.PositiveIntegerField(verbose_name='Limit'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
    ]
