# Generated by Django 4.2.1 on 2023-06-03 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_email_alter_ticket_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='description_et',
            field=models.CharField(default='', max_length=512, verbose_name='Estonian description'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='name_et',
            field=models.CharField(default='', max_length=100, verbose_name='Estonian name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='limit',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
